### PR TITLE
make upgrade to update jinja2

### PR DESCRIPTION
**Pull request by DawoudSheraz**
### Description
This PR updates the jinja2 version to 2.10.1 using `make upgrade`. See PROD-210 for more information regarding the update

### Reviewers
 - [ ] @asadazam93

### CODE REVIEW

**Comment by DawoudSheraz** [comment]
Tests are failing locally regardless of the changes. I tried locally on my branch and master. It failed on both of them.

**Comment by stvstnfrd** [comment]
Re: PROD-210 [1]

> This issue can't be viewed

This is a frequent headache for community members, CC: @natabene @nedbat 

Do you mind explaining the motivation/rationale within the commit message itself?

- [1] https://openedx.atlassian.net/browse/PROD-210

**Comment by nedbat** [comment]
Jinja 2 v2.10.1 is a security fix.

**Comment by DawoudSheraz** [comment]
> You need to add `export CUSTOM_COMPILE_COMMAND = make upgrade` in your `Makefile` and run `make upgrade` again.

We are not covering that change under PROD-210.

**Comment by awaisdar001** [comment]
> > You need to add `export CUSTOM_COMPILE_COMMAND = make upgrade` in your `Makefile` and run `make upgrade` again.
> 
> We are not covering that change under PROD-210.

Why not? I believe it's simple enough to cover here?

**Comment by DawoudSheraz** [comment]
> > > You need to add `export CUSTOM_COMPILE_COMMAND = make upgrade` in your `Makefile` and run `make upgrade` again.
> > 
> > 
> > We are not covering that change under PROD-210.
> 
> Why not? I believe it's simple enough to cover here?

PROD-210 has information about that.

**Pull request merged**
