### PR TITLE
make upgrade

### PR DESCRIPTION
**Pull request by singuliere**
As of today, travis fails on master with the following, because tox and maybe other dependencies are behind.

```
$ tox
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/bin/tox", line 10, in <module>
    sys.exit(cmdline())
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tox/session.py", line 39, in main
    config = prepare(args)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tox/session.py", line 27, in prepare
    config = parseconfig(args)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tox/config.py", line 205, in parseconfig
    pm = get_plugin_manager(plugins)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tox/config.py", line 44, in get_plugin_manager
    pm.load_setuptools_entrypoints("tox")
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/__init__.py", line 397, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/toxbat/requirements.py", line 38, in <module>
    from pip.download import PipSession
ImportError: No module named download
The command "tox" exited with 1.
```

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @singuliere! I've created [OSPR-3068](https://openedx.atlassian.net/browse/OSPR-3068) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by singuliere** [comment]
I'm unable to reproduce the [CI error locally](https://travis-ci.org/edx/xblock-sdk/builds/491544736?utm_source=github_status&utm_medium=notification): all tests are green.

```
>           raise NotImplementedError("djpyfs not available")
E           NotImplementedError: djpyfs not available
.tox/py27-django18/lib/python2.7/site-packages/xblock/reference/plugins.py:205: NotImplementedError
```

**Comment by singuliere** [comment]
For the record, I run tests locally with:

* Xvfb :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &
* getting geckodriver by copy/pasting .travis.yml
```
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz
    - mkdir geckodriver
    - tar -xzf geckodriver-v0.15.0-linux64.tar.gz -C geckodriver
    - export PATH=$PATH:$PWD/geckodriver
```
* PATH=$PATH:$PWD/../geckodriver DISPLAY=:99 tox

**Comment by singuliere** [comment]
On master tox fails locally for 1.11.10 and after an upgrade on 1.11.19 as well with

```
.tox/py27-django111/lib/python2.7/site-packages/django/template/backends/django.py:113: in get_installed_libraries
    for name in get_package_libraries(pkg):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

pkg = <module 'django.contrib.admin.templatetags' from '/home/singuliere/software/op...11/lib/python2.7/site-packages/django/contrib/admin/templatetags/__init__.pyc'>

    def get_package_libraries(pkg):
        """
        Recursively yield template tag libraries defined in submodules of a
        package.
        """
        for entry in walk_packages(pkg.__path__, pkg.__name__ + '.'):
            try:
                module = import_module(entry[1])
            except ImportError as e:
                raise InvalidTemplateLibrary(
                    "Invalid template library specified. ImportError raised when "
>                   "trying to load '%s': %s" % (entry[1], e)
                )
E               InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'django.contrib.admin.templatetags.base': cannot import name getfullargspec

.tox/py27-django111/lib/python2.7/site-packages/django/template/backends/django.py:130: InvalidTemplateLibrary
```

**Comment by natabene** [comment]
@singuliere Thank you for your contribution. Can you let me know once checks are green?

**Comment by singuliere** [comment]
In the past 15 hours, [django 1.11.20 was released](https://github.com/django/django/compare/1.11.19..1.11.20) to fix an unspecified "packaging" issue. Could this be the source of the mysterious **d 'django.contrib.admin.templatetags.base': cannot import name getfullargspec** problem observed above? Rebased & repushed, hoping a better result with 1.11.20.

**Comment by singuliere** [comment]
Whatever problem  django 1.11.19 introduced, it only had a side effect on the local testing. The tests are again working locally, [as described above](https://github.com/edx/xblock-sdk/pull/146#issuecomment-462276144).

**Comment by singuliere** [comment]
@jmbowman I'm stuck with this PR and cannot figure out the CI failure, nor can I reproduce it locally. Your help would be much appreciated. I think this PR is important as it tries to fix the CI which is currently broken (i.e. the master branch does not pass). Thanks in advance for your help :-)

**Comment by jmbowman** [comment]
The failures are due to a [new pylint check](https://github.com/edx/edx-lint/blob/master/edx_lint/pylint/unicode_check.py) we recently added in edx-lint, and your upgrade pulled in the new version.  You should just need to add `u` prefixes to the indicated format strings; this prevents them from blowing up under Python 2 when populated with non-ASCII unicode objects.  (This has bitten us a couple of times in production recently, hence the new lint check.)

**Comment by singuliere** [comment]
@jmbowman oh... the failure I was refering to is actually [NotImplementedError: djpyfs not available](https://travis-ci.org/edx/xblock-sdk/jobs/492131007#L910). But the newer failure you see hides it. Sorry for the confusion. I'll fix the newer failure as you suggest and hope for the best :-)

**Comment by singuliere** [comment]
@jmbowman the quality issues are fixed and now the [NotImplementedError: djpyfs not available](https://travis-ci.org/edx/xblock-sdk/jobs/492451530#L778) resurfaces. What a suspens :smiley:

**Comment by jmbowman** [comment]
Ok, I see the problem now (and it's passing for me locally also with your branch).  It looks like the XBlock code is silently swallowing whatever error is preventing `djpyfs` from loading; how about putting that same `from djpyfs import djpyfs` line in one of the failing tests just before the current failure, for example right before https://github.com/singuliere/xblock-sdk/blob/master/sample_xblocks/filethumbs/filethumbs.py#L77 ?  That may reveal the underlying exception.

**Comment by singuliere** [comment]
> Ok, I see the problem now (and it's passing for me locally also with your branch)

I'm so relieved :-) I thought I did a stupid newcomer mistake and created weird conditions. I'll chase this problem and fix it, starting with your suggestion to insert an import and reveal the stack trace.

**Comment by singuliere** [comment]
@jmbowman the root of the problem is boto

```
    from djpyfs import djpyfs
  File "/home/travis/build/edx/xblock-sdk/.tox/py27-django111/lib/python2.7/site-packages/djpyfs/djpyfs.py", line 18, in <module>
    from boto.s3.connection import S3Connection
  File "/home/travis/build/edx/xblock-sdk/.tox/py27-django111/lib/python2.7/site-packages/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
AttributeError: 'module' object has no attribute 'plugin'
```
and is worked around by requiring google-compute-engine for some mysterious reason (see the **upgrade boto and add google-compute-engine** commit).

This workaround is ugly but it has the merit of fixing the CI on master. I propose to investigate more and get to the bottom of it by trying to reproduce the problem locally. Or to fix whatever unexpected environmental problem causes travis to trigger the failure. However, if you would rather commit this PR as it is to unblock the CI and allow pull request to be tested, I can also investigate and find a proper fix in another PR.

What do you think?

**Comment by jmbowman** [comment]
Ah! We hit that elsewhere also, we worked around it via `export BOTO_CONFIG=/dev/null`.  There's some more context in https://github.com/edx/testeng-ci/pull/195 .

**Comment by singuliere** [comment]
I'm trying the BOTO_CONFIG=/dev/null workaround. It is equally mysterious but has the great advantage of not modifying the requirements files.

**Comment by singuliere** [comment]
Hum, unfortunately setting BOTO_CONFIG as is done in https://github.com/edx/testeng-ci/pull/195 does not fix the problem.

**Comment by jmbowman** [comment]
I think it had to specifically be in `before_install` so it's set before `boto` is installed.

**Comment by singuliere** [comment]
I tried that but ... doing it again to double check.

**Comment by nedbat** [comment]
Honestly, I'm wondering how much use this repo still gets.  @ormsbee, do you have any idea?  Or @singuliere maybe you have some information about OpenCraft's use of it?

**Comment by singuliere** [comment]
@nedbat I did not ask about **xblock-sdk** usage within OpenCraft but I will let you know. Not fixing the issue would indeed be the easy way out :-)

**Comment by bradenmacdonald** [comment]
@nedbat We don't really ever use it directly for development, but we have a lot of XBlocks that use it as a runtime for running tests (e.g. on CircleCI or Travis).

Here's [an example](https://github.com/edx-solutions/xblock-drag-and-drop-v2/blob/master/.travis.yml) (`install_test_deps.sh` installs xblock-sdk and `run_tests.py` runs selenium tests inside the workbench), but we have many.

A bunch of code to support that use case is in xblock-utils as [`SeleniumXBlockTest `](https://github.com/edx/xblock-utils/blob/770e3eea0adb45334437aeb890367f4fc81fc4cb/xblockutils/base_test.py#L34-L40).

However, we don't use xblock-sdk because we think it's the best tool for the job... I'd much rather run XBlock tests in the LMS or Studio runtimes, since it's often quite different and it's what runs the XBlocks for actual users. The problem is just that installing the LMS inside a CircleCI container to run a quick CI test job is impractical. If there were a nice self-contained docker image of the LMS that we could use for tests, then we'd probably ditch all usage of xblock-sdk and just use the LMS directly as the test environment.

**Comment by jmbowman** [comment]
Well, we do have the `edxops/edxapp` container.  It's primarily meant for use with a full devstack, but I did recently add a [make shell](https://github.com/edx/edx-platform/blob/afd262e3e1239f3ce30dc313afd39e85e6ce5f81/Makefile#L46-L51) command in edx-platform to launch it standalone for use in running `make upgrade`, tests, etc.  With some configuration work, that might work as a replacement for xblock-sdk in these tests.

**Comment by bradenmacdonald** [comment]
@jmbowman Cool, something like that could work well, yep. My only concern is that since that image doesn't include the actual `edx-platform` code, it's necessary to download that and mount it into the image; so if you don't happen to get the exact same commit of edx-platform as when the image is made, does that not sometimes require a potentially slow process to update the requirements, build static files, apply migrations, etc.? Ideally the image would include the `edx-platform` code so it's 100% ready to go, to keep the tests really fast - unless I'm missing something.

**Comment by jmbowman** [comment]
True, the existing image explicitly excludes both the repository content and the compiled static assets.  But we already have [scripts](https://github.com/edx/devstack/tree/master/scripts) to populate, archive, and restore those for the offline devstack installer.  Alternatively, we could start with something like the [tutor](https://github.com/regisb/tutor) LMS image and derive a new image which adds the necessary development packages.

**Comment by bradenmacdonald** [comment]
Ok, please let me know if anyone is interested in taking any of those things on (moving from xblock-sdk to edxapp containers for CI builds/testing). I'm happy to support that work where I can, but my plate is too full at the moment to take it on myself.

**Comment by jmbowman** [comment]
I created [TE-2866](https://openedx.atlassian.net/browse/TE-2866) to capture exploration of xblock-sdk removal options, but it'll probably be a month or more before I have much time to dig into it either.  In the meantime, can we get this PR unblocked by trying a couple more things to fix the `google-compute-engine` error?  I still don't think I've seen a Travis run that attempted to set `BOTO_CONFIG` in `before_install`, which is what's working for us in other repositories.  Here's the [underlying Travis CI issue](https://github.com/travis-ci/travis-ci/issues/7940), it has links to a pile of repositories that have successfully worked around this via various changes to `.travis.yml`.  (What would really have helped is if they'd actually fixed the problem instead of just letting it time out and auto-close.)

**Comment by OmarIthawi** [comment]
@nedbat @jmbowman I used to develop on the `edxapp` directly on my devstack. But recently it's becoming a bit slow to do that, so I started to use the SDK, especially when doing non trivial XBlock work. The XBlock ready to use workbench scenarios, are also awesome.

Sometimes I just don't care what the `edxapp` and want to do quick testing iterations, where the SDK is great. Of course, I'll end up testing it on devstack, but I find myself wanting to do that less.

With the docker devstack that "forgets" `$ pip install`s after `$ make down`, I'm more inclined to use this XBlock.

That being said, the SDK is not a total blocker not to have, but more of a pretty awesome thing to do so.

**Comment by singuliere** [comment]
> In the meantime, can we get this PR unblocked by trying a couple more things to fix the google-compute-engine error?

Sure, I'll do that. And thanks a lot for the preliminary research: it's a big help :-)

**Comment by singuliere** [comment]
For the record the root of the boto installation problem is described here: https://github.com/travis-ci/travis-ci/issues/7940#issuecomment-310759657

**Comment by singuliere** [comment]
My initial attempt at setting BOTO_CONFIG failed because I forgot tox blocks all environment variables... With a passenv BOTO_CONFIG in tox.ini it works like a charm :-)

**Comment by OmarIthawi** [comment]
Thanks @singuliere for fixing this!

**Comment by edx-webhook** [comment]
@singuliere 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/xblock-sdk&entry.867055334=https://github.com/edx/xblock-sdk/pull/146&entry.1484655318=https://github.com/singuliere&entry.752974735=2019-02-11+09:07&entry.1917517419=2019-02-21+21:33&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by jmbowman** [comment]
I forgot that GitHub now provides a "Squash and merge" option; just tried that.

**Comment by singuliere** [comment]
> I forgot that GitHub now provides a "Squash and merge" option; just tried that.

That's **great**. This way you have one commit per pull request in master but you still have the full history of commits in the pull request for forensics :+1: :tada:

**Comment by OmarIthawi** [comment]
:tada: thanks!

**Pull request merged**
