### PR TITLE
Disable ThumbsAside until we get back to working on Asides

### PR DESCRIPTION
**Pull request by nedbat**

### CODE REVIEW

**Comment by nedbat** [comment]
This is instead of #89.  @cpennington @Lyla-Fischer @doctoryes unfortunate, but the best way to get these out of people's way, yes?

**Comment by cpennington** [comment]
:+1:

**Comment by Lyla-Fischer** [comment]
:+1: Thanks

**Comment by doctoryes** [comment]
Nit: It'd be nice to add similar text to the docstring for `ThumbAside` as well.

:+1:

**Pull request merged**
