### PR TITLE
Lyla/remove filesystem example

### PR DESCRIPTION
**Pull request by Lyla-Fischer**
Removing the filethumbs example from the sample xblocks that are included in the list of standard examples. It contains an example of how to use a fairly dangerous part of the XBlock repository without explaining the potential pitfalls. See discussion in [this thread]( https://groups.google.com/forum/#!topic/edx-code/aofXeyHmaYs) on edx-code and [it's predecessor]( https://groups.google.com/forum/#!msg/edx-code/4VadWwqeMNI/K33-ilJXH1kJ)

This looks like a pretty massive removal of code, but most of these files are copies / non-git forks of other existing bits of code. Specifically, a fork of jasmine and a fork of a vanilla version of the thumbs sample XBlock are contained in this example.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @Lyla-Fischer! I've created [OSPR-984](https://openedx.atlassian.net/browse/OSPR-984) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by nedbat** [comment]
@Lyla-Fischer I need to get up to speed on this feature and its history.  I expect to have comments by the end of the week.

**Comment by nedbat** [comment]
@pmitros @cpennington Can you help me understand this?

**Comment by pmitros** [comment]
@nedbat :-1: 

This is removing a test case for a platform feature used in production on edx.org. @Lyla-Fischer removed this in her own repo to simplify things for herself, which is okay (this is an open source effort, and people are allowed to do dumb/experimental/broken things in their own forks), but that doesn't belong in edx/*. This would remove tests for a feature used in production, and which we are planning to bring into fully supported status pending review of https://github.com/edx/XBlock/pull/327. We discussed this at arch lunch a week or two ago with @ormsbee @nedbat and @cpennington. 

It would be helpful to simplify/clean up the test (which is rather large relative to what it ought to be). If @Lyla-Fischer wanted to contribute a simpler, cleaner test case, we'd all be grateful.

**Comment by Lyla-Fischer** [comment]
@pmitros in what context is it used on production? I understand that it is deployed on production as part of the XBlock repo, but it was not obvious to me which aspects of the edx-platform depend on the feature. If there is a cogent example of pyfilesystem being used in a production environment, maybe we could pull a simplified version of that example into the sdk. It would bring the test environment more into line with deployment requirements, and would make for a better example for XBlock developers that are looking to use the feature.

**Comment by pmitros** [comment]
@Lyla-Fischer For example, allowing students to upload screenshots in: 

http://edx.readthedocs.org/projects/edx-partner-course-staff/en/latest/exercises_tools/recommenderXBlock.html

This is how it is intended to be used, but unfortunately, that is not a helpful example to pull in -- it is a rather large and complex feature. It would be better to write a simple example+test case from scratch.

There are one or two similarly complex XBlocks in flight which make use of this feature (e.g. RichReview).

**Comment by cpennington** [comment]
I agree with @pmitros that we shouldn't delete a testcase/usage example of the filesystem in action. However, I can definitely understand wanting it to be: a) more concise (fewer copied chunks of code) and b) more detailed about the possible pitfalls of the filesystem field.

**Comment by nedbat** [comment]
I'm going to close this PR.  Having example code is better than not having example code.  I've opened PR #100 to add some explanation to the filethumb code.  We can work on that in that pull request.

**Pull request closed without merging**
