### PR TITLE
WIP: Enhance make-xblock script to run tests and code validation

### PR DESCRIPTION
**Pull request by azimpradhan**

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @azimpradhan! I've created [OSPR-1246](https://openedx.atlassian.net/browse/OSPR-1246) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/xblock-sdk/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by azimpradhan** [comment]
@stvstnfrd

**Comment by nedbat** [comment]
@stvstnfrd I take it that @azimpradhan is covered by the Stanford contributor agreement?

**Comment by nedbat** [comment]
@azimpradhan There are a number of choices here that we should discuss.  It might be that Stanford wants certain things that are not applicable to XBlocks in general (like Django 1.4).

**Comment by stvstnfrd** [comment]
@nedbat Indeed; @azimpradhan is one of our research assistants.

I was going to do an initial review of this before officially "handing it off" to your team.
How about I take a pass first and then we ping you in once we're ready?

**Comment by nedbat** [comment]
@stvstnfrd sounds good, thanks.

**Comment by shaunagm** [comment]
Hi @stvstnfrd, it's been three months since last activity so I'm going to close this PR.  If you want to re-open it, just ping me and I'll gladly do so.

**Pull request closed without merging**
