### PR TITLE
Move default workbench settings to an importable path

### PR DESCRIPTION
**Pull request by bradenmacdonald**
This proposed change moves `settings.py` into the `workbench` module. [Since 2011, Django recommends](https://github.com/django/django/commit/38f1fe3b35c212136d959538a309c33bf2d340a9) that the settings file be inside the main app module in order to reduce sys.path hacks.

In particular, this change will make it easier for XBlocks to use the workbench to host integration tests.

Currently, XBlocks that wish to run integration tests in the workbench (A) require that it is installed in development mode (otherwise settings.py is not even installed) and (B) need some bootstrapping code like:

```python
import workbench
# Find the location of the XBlock SDK. Note: it must be installed in development mode.
xblock_sdk_dir = os.path.dirname(os.path.dirname(workbench.__file__))
sys.path.append(xblock_sdk_dir)
# Use the workbench settings file:
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "settings")
```

With this change all that is needed is `DJANGO_SETTINGS_MODULE=workbench.settings`.

I have left a stub `settings.py` in the same place for backwards compatibility.

Note: It's hard to tell from the diff, but I made a couple minor changes to settings.py in addition to moving it: `BASE_DIR` was necessarily changed and `SRC_DIR` removed completely. This removes the behaviour where this settings file was modifying `sys.path` on import.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @bradenmacdonald! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request. 

To automatically create an OSPR issue for this pull request, just visit this link: http://openedx-webhooks.herokuapp.com/github/process_pr?number=51&repo=edx%2Fxblock-sdk

**Comment by edx-webhook** [comment]
Thanks for the pull request, @bradenmacdonald! I've created [OSPR-372](https://openedx.atlassian.net/browse/OSPR-372) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams. 

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ('this must be merged by XX date', and why that is)
- partner information ('this is a course on edx.org')
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the Github pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

We can't start reviewing your pull request until you've added yourself to the [AUTHORS](https://github.com/edx/xblock-sdk/blob/master/AUTHORS) file. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst) file for more information.

**Comment by e-kolpakov** [comment]
@bradenmacdonald :+1:

**Comment by sarina** [comment]
This seems reasonable to me. @cpennington can you please take a quick look?

**Comment by cpennington** [comment]
I'm happy to have fewer `sys.path` shenanigans. I'd love to get rid of the stub entirely, but maybe just add a deprecation warning instead, to let people know that we're going to get rid of it eventually?

**Comment by bradenmacdonald** [comment]
@cpennington That is what I did, isn't it? Though I used `warnings.warn` in the stub so it would actually be visible.

**Comment by cpennington** [comment]
Ah, you did. I'm sorry, I missed that. :+1:

**Comment by bradenmacdonald** [comment]
Thanks @cpennington and @sarina :)

**Pull request merged**
