### PR TITLE
Update docker packages

### PR DESCRIPTION
**Pull request by stvstnfrd**

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @stvstnfrd! I've created [OSPR-3307](https://openedx.atlassian.net/browse/OSPR-3307) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@stvstnfrd Thank you for your contribution. @ormsbee Is this something you could review?

**Comment by stvstnfrd** [comment]
Ping :)

**Comment by edx-webhook** [comment]
Thanks for the pull request, @stvstnfrd! I've created [OSPR-3514](https://openedx.atlassian.net/browse/OSPR-3514) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by stvstnfrd** [comment]
@natabene If @ormsbee isn't able to look at this, can you find another reviewer please?

Maybe @jmbowman ?

**Comment by natabene** [comment]
@jmbowman Would you review this?

**Comment by edx-webhook** [comment]
@stvstnfrd 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/xblock-sdk&entry.867055334=https://github.com/edx/xblock-sdk/pull/151&entry.1484655318=https://github.com/stvstnfrd&entry.752974735=2019-04-12+22:46&entry.1917517419=2019-05-24+18:34&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
