### PR TITLE
docs update for bin/workbench-make-xblock

### PR DESCRIPTION
**Pull request by Lyla-Fischer**
updated the namechange of script/startnew.py to bin/workbench-make-xblock in the docs

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @Lyla-Fischer! I've created [OSPR-906](https://openedx.atlassian.net/browse/OSPR-906) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).
We can't start reviewing your pull request until you've   added yourself to the [AUTHORS](https://github.com/edx/xblock-sdk/blob/master/AUTHORS) file . Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst) file for more information.

**Comment by sarina** [comment]
@stvstnfrd this is related to a change you made.

Anyone know why build is failing?

**Comment by sarina** [comment]
Triggered a rebuild. If it fails, @Lyla-Fischer can you add a commit to add yourself to AUTHORS? Maybe it's just cached weird, this particular PR shouldn't fail.

**Comment by sarina** [comment]
Yeah, the build failed again. Can you push another commit and see if that changes anything?

**Comment by stvstnfrd** [comment]
Thanks for the ping @sarina .

Looks like the build is passing again.

**Comment by sarina** [comment]
I assume your comment was a :+1: @stvstnfrd :smile: 

:+1: from me too

**Pull request merged**
