### PR TITLE
Upgrades workbench jquery from 1.7.2 to 2.2.3

### PR DESCRIPTION
**Pull request by pomegranited**
* Upgrades the jquery.min.js used in the workbench from 1.7.2 to 2.2.3
* Adds jquery-migrate.min.js
* Upgrades the underscore-min.js used in the workbench from 1.3.3 to 1.8.3

**JIRA tickets**: [OC-1504](https://tasks.opencraft.com/browse/OC-1504), related to FEDX initiative and [edx-platform PR 11665](https://github.com/edx/edx-platform/pull/11665).

**Testing instructions**:

    git clone https://github.com/open-craft/xblock-sdk
    git checkout -b jill/fedx-jquery2.2.x origin/jill/fedx-jquery2.2.x
    make  # installs and runs tests

**Author notes and concerns**:

1. I've only updated the workbench jquery, not the one used in the `sample_xblocks`.

**Reviewers**
- [ ] @smarnach
- [x] @bjacobel

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @pomegranited! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?number=107&repo=edx%2Fxblock-sdk

**Comment by smarnach** [comment]
Might be worth updating Underscore to whatever version edx-platform is using now at the same time.  Apart from that,  :+1:

**Comment by smarnach** [comment]
Is upstream also using jquery version 2.2.3?  I think Andy's email mentioned 2.2.2, but that might be out of date (or it might be irrelevant which micro-release to use).

**Comment by pomegranited** [comment]
@smarnach [Upstream's pending change to package.json](https://github.com/edx/edx-platform/pull/12035/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R9) shows:

        "jquery": "~2.2.0",

which maps to the most recent minor version, which was 2.2.3 when I installed, but [might be 2.2.4-pre now](https://github.com/jquery/jquery/blob/2.2-stable/package.json)?  I am hoping the minor version doesn't matter in this instance, but would welcome suggestions on how to handle this better.

**Comment by pomegranited** [comment]
@bjacobel Could you have a look at this change when you get a chance?  @smarnach recommended it while we were testing our XBlocks with your upgraded jquery 2.2.x.

**Comment by smarnach** [comment]
@pomegranited Thanks for the updates.  Sounds good to me for the micro-version, and using the latest release makes sense. :+1:

**Comment by bjacobel** [comment]
I'm not that familiar with the workbench (or with XBlocks, really) - everything here looks good to me but you might want to loop in someone more familiar with this repo to answer your concerns noted in the PR description?

**Comment by pomegranited** [comment]
No worries, @bjacobel, I wasn't sure who to ask!

@cpennington Would you be willing to review this change?

**Comment by cpennington** [comment]
This seems fine, as long as workbench is still working.

**Comment by pomegranited** [comment]
@cpennington I've tested our xblocks with this change, and they were unaffected.  Is there another way to verify the workbench is still ok?

**Comment by bradenmacdonald** [comment]
@pomegranited Aren't there a bunch of sample XBlocks that are automatically installed with the workbench when you set it up? If so, please check them. If not, then you've already done manual testing, and the tests are passing, so you should be good.

**Comment by pomegranited** [comment]
@cpennington @bradenmacdonald I've tested the sample XBlocks in the workbench, and they function the same as they did before this change, so I'm assuming all is ok.

**Pull request merged**
