### PR TITLE
Docker image build fixes

### PR DESCRIPTION
**Pull request by tiger31**
- Fixed django 2.2.0 version being not found while installing from pip (2.7 no more supported)
- Fixed manage.py being not able to import django.core package (2.7 no more supported)

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @tiger31! I've created [OSPR-4366](https://openedx.atlassian.net/browse/OSPR-4366) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@tiger31 Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions. Thanks

**Comment by nedbat** [comment]
@tiger31 Thanks for the contribution.  This pull request changes more than it should though: we don't want to push the entire structure of the repo down into a new subdirectory. I'm not sure why you want to do that.  Let's talk about the problem you are solving, and come up with another solution.

**Comment by tiger31** [comment]
Yeah, sorry, that's my fault, last commits should not appear in this PR. All because of the commands i used to push. 
```bash
git checkout docker # Forgot -b flag to create new branch
git push origin $(git branch --show-current) # And pushed to master accidentally 
```
I wanted last commits to be in different branch, just for my dev purposes. I'll rebase it in a few minutes, thaks

**Comment by tiger31** [comment]
The main problem is that after cloning repo and typing command from the readme to build container it fails because required version of django (requirements/dev.txt and requirements/base.txt) does not support python verion, that __pip__ is using

**Comment by tiger31** [comment]
Actually i'm new to python mechanics (verions, pip, etc.) but not to docker, and as it's user i want to help to improve other people experience

**Comment by natabene** [comment]
@tiger31 Have you had a chance to sign our agreement? Please let me know if you need help.

**Comment by natabene** [comment]
@tiger31 We have not heard from you in a while, so I am closing this PR for now. Please feel free to re-open if you decide to work on this again.

**Comment by edx-webhook** [comment]
@tiger31 Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/xblock-sdk&entry.867055334=https://github.com/edx/xblock-sdk/pull/170&entry.1484655318=https://github.com/tiger31&entry.752974735=2020-04-08+19:44&entry.1917517419=2020-05-05+01:27&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
