### PR TITLE
mattdrayer/update-xblock-reference: Bump to 0.4.7

### PR DESCRIPTION
**Pull request by mattdrayer**
@nedbat @doctoryes, FYI -- bumping XBlock reference from 0.4.1 to 0.4.7 in order to be able to take advantage of the new I18N support here: https://github.com/edx-solutions/xblock-drag-and-drop-v2/pull/66

### CODE REVIEW

**Comment by mattdrayer** [comment]
See this LOC for more info:  https://github.com/edx-solutions/xblock-drag-and-drop-v2/blob/master/install_test_deps.sh#L3

**Comment by mattdrayer** [comment]
Also, please let me know if I should create a new release tag for this repo, or if it's okay to continue referencing by hash.  I'd prefer to create a release tag.

**Comment by doctoryes** [comment]
Using a git tag is now the standard for a new release. It's essentially equivalent to a git hash but it has the advantage of displaying meaning in its naming.

**Comment by doctoryes** [comment]
And :+1:

**Comment by mattdrayer** [comment]
Cool -- I'm going to add an updated setup.py to this PR, then will merge and create the corresponding release tag

**Pull request merged**
