### PR TITLE
Upgrade Travis build infrastructure

### PR DESCRIPTION
**Pull request by stvstnfrd**
from legacy to container-based infrastructure

http://docs.travis-ci.com/user/migrating-from-legacy/

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @stvstnfrd! I've created [OSPR-854](https://openedx.atlassian.net/browse/OSPR-854) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by tusbar** [comment]
Hey @stvstnfrd,

Since you’re changing the travis configuration, you should probably add `pip` cache in order to speed up the CI builds (http://docs.travis-ci.com/user/caching/#pip-cache).

**Comment by stvstnfrd** [comment]
Thanks for the heads-up @tusbar .

Have you profiled this? The attached link mentions
"If you have not overridden the default install step".
Per the link there [1], it looks as if we may have "overridden the
default install step" [2]. So, I'd be curious to determine whether we'd
gain anything given our current configuration..

Any insight?

[1] http://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Installation-Step
[2] https://github.com/edx/xblock-sdk/blob/5047c7a3d409a469e2c2bf2f2a46f05a04e32df0/.travis.yml#L10

**Comment by tusbar** [comment]
@stvstnfrd you’re right, the `install` step is overridden, it runs `make pip` that just runs `pip install …`.

When you’re not overriding the `install` step, pip dependencies are not cached in the default location (travis actually overrides that) – but when you’re running `pip install` yourself, it uses the default cache location – which on linux is `~/.cache/pip`.

So you can achieve caching by adding 

```yml
cache:
  directories:
    - $HOME/.cache/pip
```

**Comment by sarina** [comment]
I'm :+1: on this change. @tusbar please feel free to merge when this meets your standards :)

**Comment by stvstnfrd** [comment]
@tusbar Caching was added as recommended.

**Comment by tusbar** [comment]
:+1:

**Pull request merged**
