### PR TITLE
Make python3 compatible

### PR DESCRIPTION
**Pull request by ffedoroff**
Make code works with python3 based for that instruction https://edx.readthedocs.io/projects/xblock-tutorial/en/latest/getting_started/create_first_xblock.html

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @ffedoroff! I've created [OSPR-4636](https://openedx.atlassian.net/browse/OSPR-4636) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by jinder1s** [comment]
Hi, thank you for creating this PR. Could you rebase off of master, it should fix your tests failing. #176 reverts breaking changes in #173

**Comment by natabene** [comment]
@ffedoroff Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions. Thanks

**Comment by ffedoroff** [comment]
@jinder1s @natabene thank you for your reply, I will try apply your suggestions soon.

**Comment by natabene** [comment]
@ffedoroff Have you had a chance to sign the agreement? Please let me know if you have questions or need help. Once agreement is signed, we can review your contribution.

**Comment by natabene** [comment]
@ffedoroff We have not heard from you for a while, so I will close this PR. Please feel free to re-open it in the future.

**Comment by edx-webhook** [comment]
@ffedoroff Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/xblock-sdk&entry.867055334=https://github.com/edx/xblock-sdk/pull/175&entry.1484655318=https://github.com/ffedoroff&entry.752974735=2020-06-03+08:38&entry.1917517419=2020-07-23+01:06&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
