### PR TITLE
[INCR 77] test with python 3.6/3.7 & django 2.0/2.1

### PR DESCRIPTION
**Pull request by singuliere**
Work In Progress, Fixes https://openedx.atlassian.net/browse/INCR-77

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @singuliere! I've created [OSPR-3066](https://openedx.atlassian.net/browse/OSPR-3066) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by jmbowman** [comment]
This is a great start on implementing Python 3 support here, and well beyond the scope of the ticket (which was meant to be just the tox.ini changes). 😄 Note that in addition to making the tickets bite-sized in terms of ease of implementation, another goal of the INCR project is keeping the changes small enough to be easily reviewed.  43 files changed is starting to stretch that a bit.

The changes so far are small enough this is probably still manageable for review, but at this point please focus on getting Travis to pass with Python 2.7 with these changes in place rather than trying to fix Python 3.6 and 3.7 support.  The Python 3 tests can either be removed from Travis or flagged as [allowed to fail](https://docs.travis-ci.com/user/customizing-the-build/#rows-that-are-allowed-to-fail) for now.  Any remaining work to fix problems under Python 3 can be written up as new INCR tickets.

Thanks for the help with this!

**Comment by natabene** [comment]
@singuliere Thank you for your contribution. Can you let me know once checks pass?

**Comment by singuliere** [comment]
blocked by https://github.com/edx/xblock-sdk/pull/146

**Comment by singuliere** [comment]
> This is a great start on implementing Python 3 support here, and well beyond the scope of the ticket (which was meant to be just the tox.ini changes)

Indeed :-) I got lost yesterday chasing and [trying to fix the CI](https://github.com/edx/xblock-sdk/pull/146) which still eludes me. I will resume work on this PR once this is done.

I'll split this PR to remove what is out of scope for INCR 77 as suggested. Do you recommend I create another PR with the remaining changes that are out of scope? If so, is there already an issue somewhere in INCR that would be in scope?

**Comment by jmbowman** [comment]
Part of the strategy with the INCR tickets has been to avoid writing tickets which are blocked on other work that hasn't been done yet (since that's usually not obvious when you're looking for something to start working on).  So in cases like this where ultimately a few different INCR tickets can be used to get to the ultimate goal, some of them may not be written until an earlier one is merged.

**Comment by singuliere** [comment]
this PR still contains all commits from #146 and #144 (required for tests to pass) and is therefore not yet ready for review. It will be rebased once #146 and #144 are merged.

**Comment by singuliere** [comment]
Rebased on top of #144 

this PR still contains all commits from #146 (required for tests to pass) and is therefore not yet ready for review. It will be rebased once #146 is merged.

**Comment by singuliere** [comment]
rebased & repushed. Last one :-P

**Comment by edx-webhook** [comment]
@singuliere 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/xblock-sdk&entry.867055334=https://github.com/edx/xblock-sdk/pull/145&entry.1484655318=https://github.com/singuliere&entry.752974735=2019-02-11+07:12&entry.1917517419=2019-02-22+21:19&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
